var curSiteRad=document.getElementById("origin-yes"),allSiteRad=document.getElementById("origin-no"),clearBtn=document.getElementById("siteRemoveBtn"),excludeContainer=document.getElementById("exclude-container"),excludeList=document.getElementById("exclude-list"),otherDiv=document.getElementById("other-type"),removeStatus=document.getElementById("remove-status"),dotdotdot=document.getElementById("dotdotdot"),gearIcon=document.querySelector(".deleting"),firstMsg=!0,siteRemoveSettings={cookies:!0,
cache:!0,cacheStorage:!0,fileSystems:!0,indexedDB:!0,localStorage:!0,serviceWorkers:!0,webSQL:!0},allRemoveSettings={cache:!0,cacheStorage:!0,cookies:!0,downloads:!0,fileSystems:!0,formData:!0,history:!0,indexedDB:!0,localStorage:!0,passwords:!1,serviceWorkers:!0,webSQL:!0};
function updateGroupItem(a){var b=a.parentElement.parentElement;a=b.previousElementSibling.firstElementChild;let c=b.querySelectorAll("input[type=checkbox]").length;b=b.querySelectorAll("input[type=checkbox]:checked").length;0===b?(a.checked=!1,a.indeterminate=!1):b===c?(a.checked=!0,a.indeterminate=!1):(a.checked=!1,a.indeterminate=!0)}
function updateChildrenItems(a){const b=a.checked;a.parentElement.nextElementSibling.querySelectorAll("input[type=checkbox]").forEach(c=>{c.disabled||(c.checked=b,c=c.id.split("-")[1],allSiteRad.checked?allRemoveSettings[c]=b:siteRemoveSettings[c]=b)})}function memSaveOptions(a){let [b,c]=this.id.split("-");"all"===b?updateChildrenItems(this):(a=this.checked,allSiteRad.checked?allRemoveSettings[c]=a:siteRemoveSettings[c]=a,updateGroupItem(this))}
function removeSiteData(){if(clearBtn.classList.contains("warn")){removeStatus.textContent="Deleting";if(allSiteRad.checked){const a={};let b=[],c=Object.assign({},allRemoveSettings);0<excludeList.childElementCount&&(c.passwords=!1,c.history=!1,c.downloads=!1,c.formData=!1,document.querySelectorAll("#exclude-list input").forEach(d=>{(d=d.value.trim())&&b.push(d)}),0<b.length&&(a.excludeOrigins=b));chrome.storage.local.set({allRemoveSettings,excludeOrigins:b});chrome.browsingData.remove(a,c,removeFinish)}else chrome.storage.local.set({siteRemoveSettings}),
chrome.browsingData.remove({originTypes:{unprotectedWeb:!0,protectedWeb:!0},origins:[curSiteRad.value]},siteRemoveSettings,removeFinish);showAnimation();clearBtn.disabled=!0}else clearBtn.classList.add("warn"),removeStatus.textContent="Click again to confirm"}
function removeFinish(){stopAnimation();clearBtn.disabled=!1;let a=document.querySelector(".error");chrome.runtime.lastError?(removeStatus.textContent="",a.textContent="Error: "+chrome.runtime.lastError.message,chrome.storage.local.set({excludeOrigins:[]})):(a.textContent="",removeStatus.textContent="Done",setTimeout(function(){clearBtn.classList.contains("warn")||(removeStatus.textContent="")},1E3),clearBtn.classList.remove("warn"),getSiteInfo())}var dotIntervalId;
function showAnimation(){gearIcon.classList.remove("display-none");dotIntervalId=setInterval(function(){dotdotdot.textContent=6>dotdotdot.textContent.length?dotdotdot.textContent+".":"."},500)}function stopAnimation(){gearIcon.classList.add("display-none");clearInterval(dotIntervalId);dotdotdot.textContent=""}
function receiveSiteInfo(a,b,c){if(b.tab){if(c=a.estimate)if(document.getElementById("storage-usage").textContent=`${filesize(c.usage,{round:1})} Storage Used`,b=document.getElementById("storage-details"),b.innerHTML="",c=c.usageDetails){let d=document.createElement("ul");for(const e in c){let f=document.createElement("li");f.textContent=`${e}: ${filesize(c[e],{round:1})}`;d.appendChild(f)}0<d.childElementCount&&b.appendChild(d)}a=a.origin;curSiteRad.value=a;document.querySelector('[for="origin-yes"]').textContent=
a;document.querySelector("h3").textContent=a;firstMsg&&(firstMsg=!1,switchOrigin(!1))}}chrome.runtime.onMessage.addListener(receiveSiteInfo);function onlyAllSite(){allSiteRad.checked=!0;curSiteRad.disabled=!0;switchOrigin(!0)}async function getSiteInfo(){const a={target:{tabId:(await chrome.tabs.query({active:!0,currentWindow:!0}))[0].id},files:["contentScript.js"]};chrome.scripting.executeScript(a,function(){chrome.runtime.lastError&&onlyAllSite()})}
function checkPermit(a){a=a.dataRemovalPermitted;for(var b in siteRemoveSettings)siteRemoveSettings[b]=siteRemoveSettings[b]&&a[b];for(const c in allRemoveSettings)allRemoveSettings[c]=allRemoveSettings[c]&&a[c];for(const c in a)!a[c]&&(b=document.getElementById("clear-"+c))&&(b.disabled=!0);getSiteInfo()}
function switchOrigin(a){a?(a=allRemoveSettings,excludeContainer.classList.remove("display-none"),0<excludeList.childElementCount?otherDiv.classList.add("display-none"):otherDiv.classList.remove("display-none")):(a=siteRemoveSettings,excludeContainer.classList.add("display-none"),otherDiv.classList.add("display-none"));for(const b in a){let c=document.getElementById("clear-"+b);c&&(c.checked=a[b])}document.querySelectorAll(".check-group").forEach(b=>updateGroupItem(b.firstElementChild.firstElementChild))}
function addExclude(a){var b=document.getElementById("exclude-tp").content;b=document.importNode(b,!0);b.querySelector("img").addEventListener("click",removeExclude);a&&(b.querySelector("input").value=a);excludeList.appendChild(b);0<excludeList.childElementCount&&otherDiv.classList.add("display-none")}function removeExclude(){this.parentElement.remove();0===excludeList.childElementCount&&otherDiv.classList.remove("display-none")}
function init(){let a=[];chrome.storage.local.get({siteRemoveSettings,allRemoveSettings,excludeOrigins:a},function(b){siteRemoveSettings=b.siteRemoveSettings;allRemoveSettings=b.allRemoveSettings;a=b.excludeOrigins;delete siteRemoveSettings.appcache;delete allRemoveSettings.appcache;chrome.browsingData.settings(checkPermit);for(b=0;b<a.length;b++)addExclude(a[b])});clearBtn.addEventListener("click",removeSiteData);curSiteRad.addEventListener("click",()=>switchOrigin(!1));allSiteRad.addEventListener("click",
()=>switchOrigin(!0));document.querySelectorAll("input[type=checkbox]").forEach(b=>b.addEventListener("click",memSaveOptions));document.getElementById("add-exclude").addEventListener("click",b=>addExclude())}init();
